apiVersion: apps/v1
kind: Deployment
metadata:
  name: belssagehr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: belssagehr
  template:
    metadata:
      labels:
        app: belssagehr
    spec:
      containers:
        - name: belssagehr
          image: hamidbels001/belssagehr:0.0.22
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: my-dockerhub-secret
---
apiVersion: v1
kind: Service
metadata:
  name: belssagehr-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: belssagehr
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30000  # Use any available port or specify your desired port
