apiVersion: apps/v1
kind: Deployment
metadata:
  name: belssagediscovery
  labels:
    app: belssagediscovery
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: belssagediscovery
  template:
    metadata:
      labels:
        app: belssagediscovery
    spec:
      containers:
        - name: belssagediscovery
          image: belssagediscovery
          imagePullPolicy: Never
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: belssagediscovery
  namespace: default
spec:
  selector:
    app: belssagediscovery
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: LoadBalancer